### ISSUE TITLE
Handling post without frontmatter image

### ISSUE THREAD

**Issue by siiron** [saigowthamr/gatsbyblog-starter#2]
Hi,

Any suggestions on how to handle posts without `image` in frontmatter? If I simply remove the `auto.jpg` and its reference (or set it to empty) in frontmatter for `second-post`, it won't render:

`TypeError: Cannot read property 'childImageSharp' of null at BlogPost`.

**Comment by saigowthamr** [comment]
Error is resolved you can check it now

**Comment by zzrez** [comment]
How did you resolve that? I did your excellent tutorial in https://codeburst.io/build-a-blog-using-gatsby-js-react-8561bfe8fc91 and had the same problem with second-post. Your final repo did not have this problem and second-post rendered correctly. I could not see difference in coding, but this must be a common issue. Thanks!

**Comment by zzrez** [comment]
I just deleted image: '' from frontmatter of second-post and still had the same error. So grateful to know how you resolved!
